### ISSUE TITLE
DEPLOIEMENT_APPLICATION GITLAB CI + HELM

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [pegasus-io/a-k8s-demo#2]
Ajouter un service `helm_operator`, basé sur : 
* un simple conteneur helm :

```bash
# installation helm 3.x
curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get-helm-3 > get_helm.sh
chmod 700 get_helm.sh
./get_helm.sh

# Exécution d'un helm chart qui déploiera mon application
helm create creshtest
cd creshtest/

echo "here editing The Helm Chart with an IDE "
helm dep list
helm dependency update .

helm template . > helm.dry.run.logs

# Helm install will actuallly deploy to the k8s cluster
helm install .

``` 

* voire https://github.com/Praqma/helmsman

Implémenter la solution suivante : 

https://about.gitlab.com/blog/2017/09/21/how-to-create-ci-cd-pipeline-with-autodeploy-to-kubernetes-using-gitlab-and-helm/

* d'abord avec un déploiement simple site web statique sur serveur HTTPD
* ensuite en déployant l'application NodeJS Express avec sa base de données mongo

**Comment by Jean-Baptiste-Lasselle** [comment]
* docker build n push to https://hub.docker.com/orgs/pegasusio : 

```bash

export OPS_HOME=$(mktemp -d -t full-release.a-k8s-demo.${HORODATAGE}.XXX)
# ---
# both app and its autopilot are versioned in the same git repo : 
# -> the Autopilot at root of the repo
# -> the Typescript / Express Application source code is
#     versioned under the './source.code/' subfolder
# 
export SSH_URI_TO_GIT_REPO=git@github.com:pegasus-io/a-k8s-demo.git
export AUTO_PILOT_RELEASE=0.0.1
export AUTO_PILOT_RELEASE=HEAD


git clone $SSH_URI_TO_GIT_REPO $OPS_HOME

$OPS_HOME
git checkout $AUTO_PILOT_RELEASE

# --- 
# -- RELEASE AUTO_PILOT : so that I don't have to build before running ops 

docker-compose -f docker-compose.build.yml build
docker login 

# docker push docker.io/pegasusio/creshtest_XXXX:${AUTO_PILOT_RELEASE}
docker push docker.io/pegasusio/creshtest_aws-cli-v2:${AUTO_PILOT_RELEASE}
docker push docker.io/pegasusio/creshtest_aws-cli-v1:${AUTO_PILOT_RELEASE}
docker push docker.io/pegasusio/creshtest_ansible_operator:${AUTO_PILOT_RELEASE}
docker push docker.io/pegasusio/creshtest_helm_operator:${AUTO_PILOT_RELEASE}
docker push docker.io/pegasusio/creshtest_kubeone_operator:${AUTO_PILOT_RELEASE}

# --- 
# -- RELEASE TYPESCRIPT / EXPRESS APP : 
#     So that I can test my helm charts, out
#     of gitlab-ci environment
#  
cd ./source.code/
export APP_RELEASE=0.0.1

docker-compose -f docker-compose.build.yml build
docker login 

# docker push docker.io/pegasusio/creshtest_app_XXXX:${APP_RELEASE}
docker push docker.io/pegasusio/creshtest_app_node:${APP_RELEASE}
docker push docker.io/pegasusio/creshtest_app_mongodb:${APP_RELEASE}

```
* CRÉER UN COMPTE https://secrethub.io/docs/guides/gitlabci/ et configurer les secrets `SECRETHUB_OCI_SECRET`, et  `SECRETHUB_K8S_SECRET`. le `AWS_SECRET_TOKEN` sera géré pureùent en interne à l'autopilote : 
  * avec un fichier dont le chemin dans le conteneur `kubeone` sera précisé via la variable `AWS_SECRET_TOKEN`, et ce chemin mappé sur un fichier externe au conteneur, de chemin `$DOCKER_COMPOSE_HOME/.secrets/aws/cloud.token`
  * avec un service HashiCorp Vault  dans le `docker-compose.yml`, et un credential helper permettant de gérer le secret `$DOCKER_COMPOSE_HOME/.secrets/aws/cloud.token`

* `./.gitlab-ci.yml` : 

```Yaml
variables:
  MY_DOCK_REGISTRY: "docker.io"
  MY_DOCKERHUB_USERNAME: "pegasusdevopsio"
  # https://secrethub.io/docs/guides/gitlabci/
  MY_DOCKERHUB_SECRETOKEN: "${SECRETHUB_OCI_SECRET}"
  # K8S_CLUSTER_SECRET is used by helm_operator_deployer in docker-compose.yml
  K8S_CLUSTER_SECRET="${SECRETHUB_K8S_SECRET}"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

# Official docker compose image.
image:
  name: docker/compose:latest
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

stages:
- build
- deploy

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  when: on_success
  only:
    - master
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - docker login -u ${MY_DOCKERHUB_USERNAME} -p ${MY_DOCKERHUB_SECRETOKEN} ${MY_DOCK_REGISTRY}
    # --- 
    # Now building and publishing the Autopilot building blocks to Dockerhub
    - docker-compose -f docker-compose.build.yml build
    - docker push $MY_DOCK_REGISTRY/pegasusio/creshtest_aws-cli-v2:${AUTO_PILOT_RELEASE}
    - docker push $MY_DOCK_REGISTRY/pegasusio/creshtest_aws-cli-v1:${AUTO_PILOT_RELEASE}
    - docker push $MY_DOCK_REGISTRY/pegasusio/creshtest_ansible_operator:${AUTO_PILOT_RELEASE}
    # Gitlab devops features include a gitlab hosted docker regsitry image. Gitlab Pipelines have
    # a built-in env. variable named '$CI_REGISTRY' That you can use to push to that registry.
    - docker push $MY_DOCK_REGISTRY/pegasusio/creshtest_helm_operator:${AUTO_PILOT_RELEASE}
    - docker push $MY_DOCK_REGISTRY/pegasusio/creshtest_kubeone_operator:${AUTO_PILOT_RELEASE}
    # --- 
    # Now building and publishing the Express TypeScript App to Dockerhub
    - cd ./source.code/ && docker-compose -f docker-compose.build.yml build
    # - cd ./source.code/ && docker push docker.io/pegasusio/creshtest_app_XXXX:${APP_RELEASE}
    - cd ./source.code/ && docker push $MY_DOCK_REGISTRY/pegasusio/creshtest_app_node:${APP_RELEASE}
    - cd ./source.code/ && docker push $MY_DOCK_REGISTRY/pegasusio/creshtest_app_mongodb:${APP_RELEASE}
    - docker logout ${MY_DOCK_REGISTRY}
  stage: deploy
  when: on_success
  only:
    - master
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    # "./.env" contains the line 'K8S_CLUSTER_SECRET=K8S_CLUSTER_SECRET_JINJA2_VAR' 
    - cd ./source.code/ && sed -i "s#K8S_CLUSTER_SECRET_JINJA2_VAR#${K8S_CLUSTER_SECRET}#g" ./.env 
    - cd ./source.code/ && docker-compose up -d helm_operator_deployer

```


* https://gitlab.com/brendan-demo/meta-meta les docker build et push doivent être réalisés comme dans cet exemple. En plus j'installerai `docker-compose`, pour exécuter `docker-compose build`
* and then helm chart execution, k8s cluster pulling images from dockerhub

**Comment by Jean-Baptiste-Lasselle** [comment]
`./.gitlab-ci.yml` : 

```Yaml
stages:
- build
- deploy

before_script:
  - docker info

build:
  stage: build
  when: on_success
  only:
    - master
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/hytta-iot/hytta.io .
    - docker push $CI_REGISTRY/hytta-iot/hytta.io
```

**Comment by Jean-Baptiste-Lasselle** [comment]
## Création du Helm Chart + Code source App NodeJS Mongo

transposition de https://www.digitalocean.com/community/tutorials/how-to-scale-a-node-js-application-with-mongodb-on-kubernetes-using-helm de digital ocean, à aws

### Code Source App

Pour avoir une exemple d'app nodejs avec mongo db branché derrière


* j'ai une app nodejs avec base de données mongodb qui marche, https://gitlab.com/second-bureau/pegasus/pokus/exterieur/infra/example-node-mongo-app.git, je peux le vérifier en exécutant : 

```bash
export DEMO_HOME=$(mktemp -d -t demo-node-mongo-XXXXXXXXXX)
export URI_TO_GIT_REPO=git@gitlab.com:second-bureau/pegasus/pokus/exterieur/infra/example-node-mongo-app

git clone $URI_TO_GIT_REPO $DEMO_HOME

cd $DEMO_HOME
docker-compose build && docker-compose up -d --force-recreate
echo ''
echo " Your app will be available at http://localhost:80/ and http://$(hostname):80/ "
echo ''
echo " To see the logs, execute this command : "
echo ''
echo " docker-compose logs -f ""
echo ''
```
Je n'ai plus qu'à aligner les noms d'images docker des deux conteneurs, le conteneur nodejs (contient client et serveur en un bloc), et le conteneur bdd


### Helm Chart

```bash
helm create helmcresh
cd helmcresh/
atom .
```
* contenu du fichier `helmcresh/values.yaml` : 

```Yaml
# Default values for nodeapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: your_dockerhub_username/node-replicas
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
# ...
```
* contenu de `helmcresh/templates/secret.yaml` : 
```Yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  # base64-encoded values
  MONGO_USERNAME: your_encoded_username
  MONGO_PASSWORD: your_encoded_password
```
* contenu de `helmcresh/templates/configmap.yaml` : 
```Yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  MONGO_HOSTNAME: "mongo-mongodb-replicaset-0.mongo-mongodb-replicaset.default.svc.cluster.local,mongo-mongodb-replicaset-1.mongo-mongodb-replicaset.default.svc.cluster.local,mongo-mongodb-replicaset-2.mongo-mongodb-replicaset.default.svc.cluster.local"  
  MONGO_PORT: "27017"
  MONGO_DB: "sharkinfo"
  MONGO_REPLICASET: "db"
```
* contenu de `helmcresh/templates/deployment.yaml` : 
```Yaml
apiVersion: apps/v1
kind: Deployment
metadata:
...
  spec:
    containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              key: MONGO_USERNAME
              name: {{ .Release.Name }}-auth
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MONGO_PASSWORD
              name: {{ .Release.Name }}-auth
        - name: MONGO_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: MONGO_HOSTNAME
              name: {{ .Release.Name }}-config
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              key: MONGO_PORT
              name: {{ .Release.Name }}-config
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              key: MONGO_DB
              name: {{ .Release.Name }}-config      
        - name: MONGO_REPLICASET
          valueFrom:
            configMapKeyRef:
              key: MONGO_REPLICASET
              name: {{ .Release.Name }}-config
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        # --- Liveness and Readiness Probes HEALTHCHECKING POD AND RUNNING APP. 
        #      Those are identically defined here, but don't have to be.
        # 
        livenessProbe:
          httpGet:
            path: /sharks
            port: http
        readinessProbe:
          httpGet:
            path: /sharks
            port: http

```
* Maintenant on peut déployer l'application dans le cluster : 
```Yaml
# Helm and kubeCTL are configured for hitting and
# authenticating the desired k8s cluster on AWS
# like with a kubeconfig file for kubectl
#
helm install --name creshtest ./helmcresh
```


#### Orchestration

* Le Atlantis lance le terraform généré par kubeone/ 
* J'ai mis en oeuvre le Terraform local-exec provisioner, pour déclencher un Ansible Playbook après le terraform apply, avec la configuration 

```yaml
provisioner "local-exec" {
    command = "ansible-playbook -i '${self.public_ip},' --private-key ${var.ssh_key_private} provision.yml"
}
```

 
* Le playbook ansible va exécuter localement : 
  * si le cluster Kubernetes n'est pas déjà existant, la commande `kubeone install config.yaml -t .` (provision du cluster k8s)
  * la commande `helm install --name creshtest ./helmcresh` (déploiement application)
  * Voici mon Playbook KubeOne / Helm cresh Local exec, Il faudra séparer en ansible roles les deux tâches suivantes, si ce n'est en deux playbook ansible distincts : 
    * `kubeone` K8S Cluster provisioning : 
```yaml
---

- name: Create the K8S cluster on AWS, using KubeOne
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  become: yes
  tasks:
    # installing KubeOne is done in the base container, now
    # we need to terraform init and then : 
    # push to SSH_URI_TO_ATLANTIS_WATCHED_GIT
    # make the first [0.0.0] release in the SSH_URI_TO_ATLANTIS_WATCHED_GIT
    # so that Atlantis get the webhook for the master branch event on the release 
    # - name: installing KubeOne is done in the base container, 
    - name: Create K8S Cluster using KubeOne
      command: kubeone install config.yaml -t . 
      debug:
        msg: " [Create K8S Cluster using KubeOne] - The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"


```
    * `Helm Chart` pour le déploiement de la Cresh App dans le K8S Cluster sur AWS : 
```yaml
---
- name: Deploy the Express TypeScript Cresh App to the K8S Cluster on AWS
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  become: yes
  tasks:
    - name: Deploy App To K8S Cluster on AWS, using Helm
      command: helm install --name creshtest ./helmcresh
      debug:
        msg: " [Deploy App To K8S Cluster on AWS, using Helm] - The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

```
* Je mettrai en oeuvre le plugin https://github.com/adammck/terraform-inventory  pour avoir l'inventaire ansible des nodes du cluster Kubernetes, par inventaire dynamique ansible, après le terraform apply : 

```bash 
ansible -m ping all -i ./path/to/thisfile
# here [./path/to/thisfile] is any executable file, that ansible will execute, and
# that ansible expects to return on its standard output stream, a string made of 
# a JSON with an expected grammar JSON Shema , specifying all 
# hosts groups and hosts meta data. Ansible doc says it has to be python, or shell script, but
# it can be any executable, as long as it returns the well formed JSON object.
# So this can be programmed in golang, like the [terraform-inventory] ansible plugin
# Or this amateur one : https://github.com/marthjod/ansible-one-inventory
# 

# terraform-inventory  executalbe file is in the current directory : 
ls -allh ./terraform-inventory || exit 1

ansible -i ./terraform-inventory  -m ping all
ansible-playbook -c kubeone-helm-playbook.yml -i ./terraform-inventory

```
* J'utiliserai le `atlantis.yaml` "_Repo level_" pour customiser le comportement d'Atlantis uniquement pour le repo git du terraform bootstrapé par `KubeOne`: [comme indiqué ici](https://www.runatlantis.io/docs/server-side-repo-config.html#example-server-side-repo), pour résoudre les dépendances ave go get avant le terraform init, et pour faire une démonstration de cette feature capitale pour l'intégration aux workflow globaux.



https://www.runatlantis.io/docs/server-configuration.html#environment-variables
