### ISSUE TITLE
mongo scale

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [pegasus-io/a-k8s-demo#21]
#  résumé

mettre en oeuvre un cluster : 
* avec N shards
* et pour chaque shard, un replicaSet : 
  * de `P_1` répliques , pour le shard no. `1`
  *  ...
  * de `P_N` répliques , pour le shard no. `N`

## article trouvé sur stackexchange

<div class="post-layout">
        <div class="votecell post-layout--left">
            
<div class="js-voting-container grid fd-column ai-stretch gs4 fc-black-200" data-post-id="53705">
        <button class="js-vote-up-btn grid--cell s-btn s-btn__unset c-pointer" title="This answer is useful" aria-pressed="false" aria-label="up vote" data-selected-classes="fc-theme-primary"><svg aria-hidden="true" class="svg-icon m0 iconArrowUpLg" width="36" height="36" viewBox="0 0 36 36"><path d="M2 26h32L18 10 2 26z"></path></svg></button>
        <div class="js-vote-count grid--cell fc-black-500 fs-title grid fd-column ai-center" itemprop="upvoteCount" data-value="125">125</div>
        <button class="js-vote-down-btn grid--cell s-btn s-btn__unset c-pointer" title="This answer is not useful" aria-pressed="false" aria-label="down vote" data-selected-classes="fc-theme-primary"><svg aria-hidden="true" class="svg-icon m0 iconArrowDownLg" width="36" height="36" viewBox="0 0 36 36"><path d="M2 10h32L18 26 2 10z"></path></svg></button>

    
            <div class="js-accepted-answer-indicator grid--cell fc-green-500 ta-center py4" title="loading when this answer was accepted..." tabindex="0" role="note" aria-label="accepted">
                <svg aria-hidden="true" class="svg-icon iconCheckmarkLg" width="36" height="36" viewBox="0 0 36 36"><path d="M6 14l8 8L30 6v8L14 30l-8-8v-8z"></path></svg>
            </div>

    
        <a class="js-post-issue grid--cell s-btn s-btn__unset c-pointer py8 mx-auto" href="/posts/53705/timeline" data-shortcut="T" title="Timeline"><svg aria-hidden="true" class="svg-icon mln2 mr0 iconHistory" width="19" height="18" viewBox="0 0 19 18"><path d="M3 9a8 8 0 1 1 3.73 6.77L8.2 14.3A6 6 0 1 0 5 9l3.01-.01-4 4-4-4h3L3 9zm7-4h1.01L11 9.36l3.22 2.1-.6.93L10 10V5z"></path></svg></a>

</div>

        </div>

        

<div class="answercell post-layout--right">
    
    <div class="post-text" itemprop="text">
<p>A <a href="http://docs.mongodb.org/manual/core/replica-set-members/"><strong>Replica-Set</strong></a> means that you have multiple instances of MongoDB which each mirror all the data of each other. A replica-set consists of one Master (also called "Primary") and one or more Slaves (aka Secondary). Read-operations can be served by any slave, so you can increase read-performance by adding more slaves to the replica-set (provided that your client application is capable to actually use different set-members). But write-operations always take place on the master of the replica-set and are then propagated to the slaves, so writes won't get faster when you add more slaves.</p>

<p>Replica-sets also offer fault-tolerance. When one of the members of the replica-set goes down, the others take over. When the master goes down, the slaves will elect a new master. For that reason <a href="http://docs.mongodb.org/manual/core/replica-set-members/">it is suggested</a> for productive deployment to always use MongoDB as a replica-set of at least three servers, two of them holding data (the third one is a data-less "arbiter" which is required for determining a new master when one of the slaves goes down).</p>

<p>A <a href="http://docs.mongodb.org/manual/core/sharded-cluster-architectures-production/"><strong>Sharded Cluster</strong></a> means that each shard of the cluster (which can also be a replica-set) takes care of a part of the data. Each request, both reads and writes, is served by the cluster where the data resides. This means that both read- and write performance can be increased by adding more shards to a cluster. Which document resides on which shard is determined by the <em>shard key</em> of each collection. It should be chosen in a way that the data can be evenly distributed on all clusters and so that it is clear for the most common queries where the shard-key resides (example: when you frequently query by <code>user_name</code>, your shard-key should include the field <code>user_name</code> so each query can be delegated to only the one shard which has that document).</p>

<p>The drawback is that the fault-tolerance suffers. When one shard of the cluster goes down, any data on it is inaccessible. For that reason each member of the cluster should also be a replica-set. This is not required. <a href="http://docs.mongodb.org/manual/core/sharded-cluster-architectures-test/">When you don't care about high-availability, a shard can also be a single mongod instance without replication</a>. But <a href="http://docs.mongodb.org/manual/core/sharded-cluster-architectures-production/">for production-use you should always use replication</a>.</p>

<h2>So what does that mean for your example?</h2>

<pre class="lang-sql prettyprint prettyprinted" style=""><code><span class="pln">                            Sharded Cluster             
             </span><span class="pun">/</span><span class="pln">                    </span><span class="pun">|</span><span class="pln">                    </span><span class="pun">\</span><span class="pln">
      Shard A                  Shard B                  Shard C
        </span><span class="pun">/</span><span class="pln"> </span><span class="pun">\</span><span class="pln">                      </span><span class="pun">/</span><span class="pln"> </span><span class="pun">\</span><span class="pln">                      </span><span class="pun">/</span><span class="pln"> </span><span class="pun">\</span><span class="pln">
</span><span class="pun">+</span><span class="com">-------+ +---------+    +-------+ +---------+    +-------+ +---------+</span><span class="pln">
</span><span class="pun">|</span><span class="kwd">Primary</span><span class="pun">|</span><span class="pln"> </span><span class="pun">|</span><span class="pln">Secondary</span><span class="pun">|</span><span class="pln">    </span><span class="pun">|</span><span class="kwd">Primary</span><span class="pun">|</span><span class="pln"> </span><span class="pun">|</span><span class="pln">Secondary</span><span class="pun">|</span><span class="pln">    </span><span class="pun">|</span><span class="kwd">Primary</span><span class="pun">|</span><span class="pln"> </span><span class="pun">|</span><span class="pln">Secondary</span><span class="pun">|</span><span class="pln">
</span><span class="pun">|</span><span class="pln">  </span><span class="lit">25</span><span class="pln">GB </span><span class="pun">|=|</span><span class="pln"> </span><span class="lit">25</span><span class="pln">GB    </span><span class="pun">|</span><span class="pln">    </span><span class="pun">|</span><span class="pln"> </span><span class="lit">25</span><span class="pln"> GB </span><span class="pun">|=|</span><span class="pln"> </span><span class="lit">25</span><span class="pln"> GB   </span><span class="pun">|</span><span class="pln">    </span><span class="pun">|</span><span class="pln"> </span><span class="lit">25</span><span class="pln">GB  </span><span class="pun">|=|</span><span class="pln"> </span><span class="lit">25</span><span class="pln">GB    </span><span class="pun">|</span><span class="pln">   
</span><span class="pun">+</span><span class="com">-------+ +---------+    +-------+ +---------+    +-------+ +---------+</span></code></pre>

<p>When you want to split your data of 75GB into 3 shards of 25GB each, you need at least 6 database servers organized in three replica-sets. Each replica-set consists of two servers who have the same 25GB of data. </p>

<p>You also need servers for the arbiters of the three replica-sets as well as the mongos router and the config server for the cluster. The arbiters are very lightweight and are only needed when a replica-set member goes down, so they can usually share the same hardware with something else. But Mongos router and config-server should be redundant and on their own servers.</p>
    </div>
    <div class="grid mb0 fw-wrap ai-start jc-end gs8 gsy">
        <time itemprop="dateCreated" datetime="2013-11-21T12:59:39"></time>
        <div class="grid--cell mr16" style="flex: 1 1 100px;">
            

<div class="post-menu"><a href="/a/53705" rel="nofollow" itemprop="url" class="js-share-link js-gps-track" title="short permalink to this answer" data-gps-track="post.click({ item: 2, priv: 0, post_type: 2 })" data-controller="se-share-sheet s-popover" data-se-share-sheet-title="Share a link to this answer" data-se-share-sheet-subtitle="" data-se-share-sheet-post-type="answer" data-se-share-sheet-social="facebook twitter " data-se-share-sheet-location="2" data-s-popover-placement="bottom-start" aria-controls="se-share-sheet-1" data-action=" s-popover#toggle se-share-sheet#preventNavigation s-popover:show->se-share-sheet#willShow s-popover:shown->se-share-sheet#didShow">share</a><div class="s-popover z-dropdown" style="width: unset; max-width: 28em;" id="se-share-sheet-1"><div class="s-popover--arrow"></div><div><span class="js-title fw-bold">Share a link to this answer</span> <span class="js-subtitle"></span></div><div class="my8"><input type="text" class="js-input s-input wmn3 sm:wmn-initial" readonly=""></div><div class="d-flex jc-space-between mbn4"><button class="js-copy-link-btn s-btn s-btn__link">Copy link</button><div class="js-social-container"></div></div></div><span class="lsep">|</span><a href="/posts/53705/edit" class="suggest-edit-post js-gps-track" data-gps-track="post.click({ item: 6, priv: 0, post_type: 2 })" title="">improve this answer</a><span class="lsep">|</span><button id="btnFollowPost-53705" class="s-btn s-btn__link fc-black-400 h:fc-black-700 px4 pb2 js-follow-post js-follow-answer js-gps-track" role="button" data-gps-track="post.click({ item: 14, priv: 0, post_type: 2 })" data-controller="s-tooltip " data-s-tooltip-placement="bottom" data-s-popover-placement="bottom" aria-controls="" aria-describedby="--stacks-s-tooltip-rt9kgrel">
        follow
    </button><div id="--stacks-s-tooltip-rt9kgrel" class="s-popover s-popover__tooltip pe-none" aria-hidden="true" role="tooltip">Follow this answer to receive notifications<div class="s-popover--arrow"></div></div><span class="lsep">|</span><span class="lsep">|</span><span class="lsep">|</span><span class="lsep">|</span></div>

        </div>
    <div class="post-signature grid--cell fl0">
<div class="user-info ">
    <div class="user-action-time">
        <a href="/posts/53705/revisions" title="show all edits to this post" class="js-gps-track" data-gps-track="post.click({ item: 4, priv: 0, post_type: 2 })">edited <span title="2015-09-17 08:11:44Z" class="relativetime">Sep 17 '15 at 8:11</span></a>
    </div>
    <div class="user-gravatar32">
        
    </div>
    <div class="user-details">
        
        <div class="-flair">
            
        </div>
    </div>
</div>    </div>

    <div class="post-signature grid--cell fl0">
        <div class="user-info user-hover">
    <div class="user-action-time">
        answered <span title="2013-11-21 12:59:39Z" class="relativetime">Nov 21 '13 at 12:59</span>
    </div>
    <div class="user-gravatar32">
        <a href="/users/30790/philipp"><div class="gravatar-wrapper-32"><img src="https://www.gravatar.com/avatar/24231f169c1ed55850339ec5d62047c5?s=32&amp;d=identicon&amp;r=PG" alt="" class="bar-sm" width="32" height="32"></div></a>
    </div>
    <div class="user-details" itemprop="author" itemscope="" itemtype="http://schema.org/Person">
        <a href="/users/30790/philipp">Philipp</a><span class="d-none" itemprop="name">Philipp</span>
        <div class="-flair">
            <span class="reputation-score" title="reputation score " dir="ltr">1,435</span><span title="1 gold badge" aria-hidden="true"><span class="badge1"></span><span class="badgecount">1</span></span><span class="v-visible-sr">1 gold badge</span><span title="8 silver badges" aria-hidden="true"><span class="badge2"></span><span class="badgecount">8</span></span><span class="v-visible-sr">8 silver badges</span><span title="7 bronze badges" aria-hidden="true"><span class="badge3"></span><span class="badgecount">7</span></span><span class="v-visible-sr">7 bronze badges</span>
        </div>
    </div>
</div>

    </div>
    </div>
    
</div>

                <div class="post-layout--right">
        <div id="comments-53705" class="comments js-comments-container bt bc-black-2 mt12 " data-post-id="53705" data-min-length="15">
            <ul class="comments-list js-comments-list" data-remaining-comments-count="0" data-canpost="false" data-cansee="true" data-comments-unavailable="false" data-addlink-disabled="true">

                        <li id="comment-96524" class="comment js-comment " data-comment-id="96524">
        <div class="js-comment-actions comment-actions">
            <div class="comment-score js-comment-edit-hide">
                    <span title="number of 'useful comment' votes received" class="cool">2</span>
            </div>
        </div>
        <div class="comment-text js-comment-text-and-form">
            <div class="comment-body js-comment-edit-hide">
                
                <span class="comment-copy">Thanks a lot for the detail answer...one more question...if the primary is down while a write or read operation is being carried out then..1) what is the delay in selecting the primary from the secondaries and 2) during that delay where will be the data be stored temporarily?</span>
                
–&nbsp;<a href="/users/29980/saad-saadi" title="973 reputation" class="comment-user owner">Saad Saadi</a>
                <span class="comment-date" dir="ltr"><a class="comment-link" href="#comment96524_53705"><span title="2013-11-22 06:58:18Z" class="relativetime-clean">Nov 22 '13 at 6:58</span></a></span>
            </div>
        </div>
    </li>
    <li id="comment-96526" class="comment js-comment " data-comment-id="96526">
        <div class="js-comment-actions comment-actions">
            <div class="comment-score js-comment-edit-hide">
                    <span title="number of 'useful comment' votes received" class="cool">4</span>
            </div>
        </div>
        <div class="comment-text js-comment-text-and-form">
            <div class="comment-body js-comment-edit-hide">
                
                <span class="comment-copy">@SaadSaadi <a href="http://docs.mongodb.org/manual/core/replica-set-elections/" rel="nofollow noreferrer">The primary election process is described in the documentation</a>. It takes between 10 and 12 seconds for the secondaries to notice that the primary is down. The primary election itself will usually only take milliseconds. The replica-set is read-only while there is no primary. Any attempts from applications to write data during this time will fail.</span>
                
–&nbsp;<a href="/users/30790/philipp" title="1,435 reputation" class="comment-user">Philipp</a>
                <span class="comment-date" dir="ltr"><a class="comment-link" href="#comment96526_53705"><span title="2013-11-22 08:23:53Z" class="relativetime-clean">Nov 22 '13 at 8:23</span></a></span>
            </div>
        </div>
    </li>
    <li id="comment-209359" class="comment js-comment " data-comment-id="209359">
        <div class="js-comment-actions comment-actions">
            <div class="comment-score js-comment-edit-hide">
                    <span title="number of 'useful comment' votes received" class="cool">1</span>
            </div>
        </div>
        <div class="comment-text js-comment-text-and-form">
            <div class="comment-body js-comment-edit-hide">
                
                <span class="comment-copy">@Philipp: Just two comments: (1) the shard key cannot be modified (i.e. you cannot shard using a different key) and (2) you can read from the secondary nodes of the replica set but consistency depends from the write concern (in order to be consistent the w option should be equal to the replica set sth which is not viable since each shard may have different replica set sizes deliberately or due to node failures).</span>
                
–&nbsp;<a href="/users/62315/mike-argyriou" title="101 reputation" class="comment-user">Mike Argyriou</a>
                <span class="comment-date" dir="ltr"><a class="comment-link" href="#comment209359_53705"><span title="2015-09-17 09:30:38Z" class="relativetime-clean">Sep 17 '15 at 9:30</span></a></span>
                        <span title="this comment was edited 1 time">
                            <svg aria-hidden="true" class="svg-icon va-text-bottom o50 iconPencilSm" width="14" height="14" viewBox="0 0 14 14"><path d="M11.1 1.71l1.13 1.12c.2.2.2.51 0 .71L11.1 4.7 9.21 2.86l1.17-1.15c.2-.2.51-.2.71 0zM2 10.12l6.37-6.43 1.88 1.88L3.88 12H2v-1.88z"></path></svg>
                        </span>
            </div>
        </div>
    </li>
    <li id="comment-407877" class="comment js-comment " data-comment-id="407877">
        <div class="js-comment-actions comment-actions">
            <div class="comment-score js-comment-edit-hide">
            </div>
        </div>
        <div class="comment-text js-comment-text-and-form">
            <div class="comment-body js-comment-edit-hide">
                
                <span class="comment-copy">@Philipp can you please answer further follow up questions on <a href="https://dba.stackexchange.com/questions/208482/sharding-and-replication-on-mongodb" title="sharding and replication on mongodb">dba.stackexchange.com/questions/208482/…</a> ?</span>
                
–&nbsp;<a href="/users/129987/user3198603" title="315 reputation" class="comment-user">user3198603</a>
                <span class="comment-date" dir="ltr"><a class="comment-link" href="#comment407877_53705"><span title="2018-06-01 13:37:49Z" class="relativetime-clean">Jun 1 '18 at 13:37</span></a></span>
            </div>
        </div>
    </li>

            </ul>
	    </div>

        <div id="comments-link-53705" data-rep="50" data-anon="true">
                    <a class="js-add-link comments-link disabled-link" title="Use comments to ask for more information or suggest improvements. Avoid comments like “+1” or “thanks”." href="#" role="button">add a comment</a>
                <span class="js-link-separator dno">&nbsp;|&nbsp;</span>
            <a class="js-show-link comments-link dno" title="expand to show all comments on this post" href="#" onclick="" role="button"></a>
        </div>         
    </div>
    </div>

**Comment by Jean-Baptiste-Lasselle** [comment]
* https://docs.mongodb.com/manual/tutorial/deploy-shard-cluster/
* https://www.howtoforge.com/tutorial/deploying-mongodb-sharded-cluster-on-centos-7/ : pour ce tuto, changerla policy SELinux, en suicvant les recommandations officielles https://docs.mongodb.com/manual/tutorial/install-mongodb-on-red-hat/ (pour voir si les shards marchent toujours)

# Brouillon 

```bash
# on the centos hosts, so that matches my containers

# --- # 
# To disable SELinux
sudo sed -i "s#SELINUX=*#SELINUX=disabled#g" /etc/sysconfig/selinux 

# -- reboot host

# 

```


* ansible virtual inventory (each hosts is a container) (will become base k8s services) : 
```ini
# --- # 
# 2 centOS 7 server as Config Replica Sets
# --- # 
[mongo-config-services]
10.0.15.31      configsvr1
10.0.15.32      configsvr2
# --- # 
#  4 CentOS 7 server as Shard Replica Sets
# --- # 
[mongo-shards]
10.0.15.21      shardsvr1
10.0.15.22      shardsvr2
10.0.15.23      shardsvr3
10.0.15.24      shardsvr4

1 CentOS 7 server as mongos/Query Router
[mongo-query-router]
10.0.15.11      mongos
```
* linux user etc in container : we'll see that later. We test as root first, erase any issue, then we'll lower permissions as low as possible, and use non root users everywhere, should it take installing `sudo` and edit a custom `/etc/sudoers.d/mongo.sudoers` configuration.
* Each server connected to another server

So alright, we have a basic K8S resources definition layout here, plus I believe we need a stateful set for each service (router, config, and mongo)  : 

```bash
# mongo config server service
config-server/mongo-config-server-service.yaml
config-server/mongo-config-server-statefulset.yaml
# mongo shards service
router/mongo-shards-service.yaml
router/mongo-shards-statefulset.yaml
# mongo query router service
router/mongo-query-router-service.yaml
router/mongo-query-router-statefulset.yaml
```

* `mongo-query-router-service.yaml` : 

```Yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo-qrouter
  labels:
    app: mongo-qrouter
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - port: 27017
      name: mongo-qrouter
  selector:
    app: mongo-qrouter
```

* `mongo-query-router-statefulset.yaml`

```Yaml
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mongo-qrouter
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mongo-qrouter
  template:
    metadata:
      labels:
        app: mongo-qrouter
    spec:
      containers:
        - name: mongo-qrouter
          image: 'pegasusio/mongo-qrouter:0.0.1'
          args:
            - mongo
            - '--config-opt-1'
            - 'valueConfOpt1'
            # [...] and as many args as needed to start properly mongo qrouter process
          ports:
            - containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_ENV_VAR_1
              value: mongorocks
           # use hashicorp vault secret management here, from 
           # kubernetes secret manager integration
            - name: MONGO_SECRET
              value: SD-6sfdsfggsTHGdfggsdfgjsd
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /mongo-qrouter-data
          livenessProbe:
            httpGet:
              path: /test
              port: 27017
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /test
              port: 27017
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
#           terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler

  # Volume Claims will be launched with scaling out shards with this stateful set , based on
  # this template (10 Gib each shard) : 
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: mongo-qrouter
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        volumeMode: Filesystem
      status:
        phase: Pending
  serviceName: mongo-qrouter
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
status:
  replicas: 4
```

* `mongo-shards-service.yaml` : 
```Yaml
kind: Service
apiVersion: v1
metadata:
  name: mongo-shards
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 37017
  selector:
    app: mongo-shards
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}
```
* `mongo-shards-statefulset.yaml`

```Yaml
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mongo-shards
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mongo-shards
  template:
    metadata:
      labels:
        app: mongo-shards
    spec:
      containers:
        - name: mongo-shards
          image: 'pegasusio/mongo-shards:0.0.1'
          args:
            - mongo
            - '--config-opt-1'
            - 'valueConfOpt1'
            # [...] and as many args as needed to start properly mongo shard process
          ports:
            - containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_ENV_VAR_1
              value: mongorocks
           # use hashicorp vault secret management here, from 
           # kubernetes secret manager integration
            - name: MONGO_SECRET
              value: SD-6sfdsfggsTHGdfggsdfgjsd
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /mongo-shards-data
          livenessProbe:
            httpGet:
              path: /test
              port: 27017
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /test
              port: 27017
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
#           terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler

  # Volume Claims will be launched with scaling out shards with this stateful set , based on
  # this template (10 Gib each shard) : 
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: mongo-shard
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        volumeMode: Filesystem
      status:
        phase: Pending
  serviceName: mongo-shard
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
status:
  replicas: 4
```
* Same statefulset / service duet for `mongo-config-server-service.yaml`, and  `mongo-config-server-statefulset.yaml`
